name: Build CLI and print hash

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm]
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Docker
        uses: docker/setup-docker-action@efe9e3891a4f7307e689f2100b33a155b900a608 # v4.5.0
      - name: Build using Docker
        run: |
          # MOPS_VERSION=$(cd cli && npm pkg get version | tr -d \")
          # echo MOPS_VERSION=$MOPS_VERSION
          # if [ -z "$MOPS_VERSION" ]; then
          #   echo "MOPS_VERSION is empty"
          #   exit 1
          # fi
          MOPS_VERSION=0.0.0
          cd cli
          docker build . --build-arg COMMIT_HASH=${{ github.sha }} --build-arg MOPS_VERSION=$MOPS_VERSION -t mops
          OUTPUT=$(docker run --rm mops || echo ".")
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
