name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        mops-version: [ic-mops@1.0.0, ./cli/dist]
        moc-version: [0.14.13]
        node-version: [20]

    runs-on: ubuntu-latest
    name: node ${{ matrix.node-version }}, moc ${{ matrix.moc-version }}, ${{ matrix.mops-version }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.17
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.17

      - uses: dfinity/setup-dfx@main

      - name: Cache mops packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: mops-packages-${{ runner.os }}-${{ hashFiles('mops.toml') }}
          restore-keys: |
            mops-packages-${{ runner.os }}-${{ hashFiles('mops.toml') }}
            mops-packages-${{ runner.os }}
          path: |
            ~/.cache/mops
            ~/Library/Caches/mops

      - name: Install npm packages
        run: bun install

      - name: Build local cli
        if: ${{ matrix.mops-version == './cli/dist' }}
        run: cd cli && npm run prepare

      - name: Install mops
        run: npm i -g ${{ matrix.mops-version }}

      - name: Install mops packages
        run: mops install

      - name: Select moc version
        run: mops toolchain use moc ${{ matrix.moc-version }}

      - name: Run replica
        run: npm run replica

      - name: Deploy backend
        run: npm run deploy-local

      - name: Build frontend
        run: npm run build-frontend

      - name: Build docs
        run: npm run build-docs

      - name: Build blog
        run: npm run build-blog

      - name: Build CLI releases
        run: npm run build-cli-releases

      - name: Run CLI tests
        run: cd cli && npm test
